# Generated by Django 5.1.5 on 2025-01-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_carouselimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselimage',
            old_name='image',
            new_name='image_ads',
        ),
    ]
