# Generated by Django 5.1.5 on 2025-01-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_image_carouselimage_image_ads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
