# Generated by Django 5.1.5 on 2025-02-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
