# Generated by Django 5.1.5 on 2025-03-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='product_name',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
