# Generated by Django 4.2.4 on 2025-03-12 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customer'),
        ('cart', '0002_delete_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_order_items', to='store.product'),
        ),
    ]
