# Generated by Django 4.2.4 on 2025-03-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
